### ISSUE TITLE
Settings not separated by client computer user account on OSX

### ISSUE THREAD

**Issue by alexmbaker** [pydio/pydio-sync#78]
It is possible that the issue described below is partially an result of a whole series of errors making it difficult to know if i am reporting the true issue or simply observing symptomatic effects of some other problem.  If someone could let me know how I can delete all local configuration data using bash or finder I will happily run the tests again and provide a more detailed description and screen shots.

# Environment

Server = Pydio 6.0.2 on Ubuntu Server 14.04 LTS, Apache2
Client = Mac OSX Yosemite, unknown client version as the "About" menu does not work

Client computer has 2 user accounts, Alex and Jodie

# Steps to reproduce 

* Start Computer
* Log in as Alex
* Switch users and Log in as Jodie
* Download and install the latest pydio-sync client taken from website 11 Jan 2015
* Configure Client to connect to server and synchronise whole workspace
* Switch users back to Alex

# Expected Results

* Pydio Client under user Alex should not show Jodie's configuration
* Pydio Client should not default to synchronise to user Alex's Pydio directory in Alex's home folder

# Actual Results

* Pydio Client shows 3 synchronisation profiles under both user accounts
* When user Jodie was creating the synchronisation profile the pre-selected folder to synchronise data was /Users/alex/Pydio

**Comment by cdujeu** [comment]
Hi Alex, 
Not sure we can support this usecase "as is". Could you actually try not to "switch user" but to actually close the session and log in on another session?
-c

**Comment by Flauschbaellchen** [comment]
@alexmbaker, I found the same issue and as it seems it is a general one for all OS.
I reported it (https://pyd.io/f/topic/client-security-in-multi-user-environments) but as the forum is not fully visible to guests I quote it here:

Myself (Noxx), February 6, 2015 at 12:06 pm
>Hi there,

>I just played a bit around with the new pydio client (v6, Linux/Ubuntu) prior to rolling it out to all my client computers.
>Please correct me if I’m wrong but as far as I’ve found out:

>The client is just a simple browser layer.
>It opens the frontend of the agent which runs in the background.
>The configuration on this agent is not user-based, thus in an multi-user environment each user can see all configured shares another user set up.
>But not enough, it’s also possible to edit and delete these shares.
>Additionally, if an user has only shell access, it is possible to forward the agent’s port to its own computer and access the frontend there.

>All in all, it’s a security nightmare.

>Any plans on restict/fix this?
>Or is there another configuration setting I didn’t found yet?

>Greetings~

Charles, February 6, 2015 at 3:07 pm
>Hi Noxx,
>to make it short:
>. You’ve understood well the architecture (daemon + UI).
>. Indeed it’s not multi-user yet: the agent starts under a given user, so if you switch users, it does not restart with the other user home. This is something we are working on, quite complicated as it is very os-specific.
>. About the security concern, if one has access to a shell and ability to forward ports, one has probably the ability to modify a config file on the client machine. That said, the daemon should in any case only allow localhost connection. But maybe I’m wrong, would be glad if you elaborate.
>-c


Myself (Noxx), February 9, 2015 at 9:09 am
>Hi charles,

>thanks for the fast answer.

>You don’t need any special perms to forward ports if you have shell access.
>I run the test with: “ssh user@maschine -L 5556:localhost:5556″
>Afterwards you can access the remote agent at the same port on your machine as it runs on the remote one.
>On the remote side it looks like a local connection, thus a “listen-only-to-localhost” does not restrict this access.

>I’ve just tested it on a windows machine.. obviously it suffers from the same issue.
>It’s possible to access the pydio agent from a temporary guest account, too.

>Because you have access to the *complete* agent configuration, it’s easy to change the destination path of a sync or the workspace it’s working on.
>THIS HAS A CRITICAL SECURITY IMPACT! as it gives any user full access to all files and folders of the original user!

>The current setup and the idea to run it as a webservice is a nice idea, but as far as I can think it’s totally flawed.
>I don’t see an easy solution to restrict a global running service listening on a port everyone can connect to to a single user.
>Additionally, even if you could, you cannot hardcode the port as it would not allow to run multiple instances of the agent (one for every user).
>If you leave it in the current state allowing it to serve multiple users, it would need a seperate login page and to start as root as it would need the permissions to write files to every user’s home directories (and that would be a negative point, too)

>Is it possible to get a roughly estimation, if and when this issue can be resolved – or what priority it has?
>I would like to use pydio in a production environment but currently it’s not usable.
>And (the client) should not even be distributed in this state.

>Sorry if my words seems a bit harsh.
>If you need any further information, feel free to ask.

>Greetings, Noxx

**Comment by cdujeu** [comment]
Hi Guys
Ok my idea for that would be to simply add an Http Digest-Auth mechanism, with a local login/password that would be stored in a file. That way if you want to open the config in a browser, you have to find this file first, and we can have the Qt systray automatically get that file and use the given credentials. 
This credential file could be generated at each agent start, stored in user "local" location, and thus inaccessible if you don't have a real access to the user account.
what do you think?
-c

**Comment by cdujeu** [comment]
this has a super-high priority of course

**Comment by Flauschbaellchen** [comment]
Hi Charles,
I'm fine with every hotfix that would fixes the possibility to edit another user's configuration and thus get access over all files ;)


Regarding an agent for multi-user environments:
It would be possible to check which user logged in via digest-auth and thus representing personal configurations for each user.
However, afaik the agent would need to run as root to read/move/copy/edit files for every user.
That would leave the possibility to accidentally mess up files.
Either by exploit or by not checking carefully if the logged-in user has access to requested resources.

Don't know if this helps; I don't have much knowledge in this field of experience - but how about sockets?
E.g:
* Agent runs as the user starting it; creates socket in $HOME/.pydio (or similiar to cfg) with 0600
* Client can access the socket in its standard location

Greetings~

**Comment by cdujeu** [comment]
Mmm, not sure we want to switch to socket now...
I don't get why you say that the "agent would need to run as root to read/move/copy/edit files for every user." 
The idea would be to actually store the digest key under something like $HOME/.pydio/ 
So each agent would only have to access the local user data
no?

**Comment by Flauschbaellchen** [comment]
Well, yes, but that won't fix the multi-user issue.
Currently you can only start one agent at a time as the port is occupied.
Thus, after UserA has started his agent, UserB can't access it because of the http-auth (good) but cannot start his own one.

Ok, as these are two issues (one for the permission-exploit, one for not beeing multi-user) it would be maybe better to discuss this separately, too.

**Comment by cdujeu** [comment]
"you can only start one agent at a time as the port is occupied." 
Actually that's not the case, the agent detects if a port is occupied, and will automatically switch to another port, writing down its new port inside the "AppLocalData"/port_config file. So we can add the auth info to that file.

**Comment by cdujeu** [comment]
I can verify that with the latest build version, on windows for example: if I switch user, it starts a new agent on another port.

**Comment by cdujeu** [comment]
I don't know how "user switching" is working on linux.
On Mac it's yet another issue, as the "fast user switching" is a bit complicated to handle. 
I guess at least the auth mechanism fixes the security issue, right?

**Comment by Flauschbaellchen** [comment]
Hi charles,

sorry, my fault. I redownloaded the latest dev version and tested it again. Now it works.

Than just another question:
What would be different, if switching to sockets?
Afaik it's more or less the same as connecting to ports. Please correct me if I'm wrong.
Maybe there are OS-specific problems/not supported everywhere?

Currently, we would have the following status after the http-auth solution:
* Agent needs his own port, if another agent is running/port is occupied, it needs to switch to another one.
* If an agent is started twice, it runs twice.. no checking is (currently) done.
* http-auth to restrict access to only the original user; random password is generated at each start

This status defends the really nice idea to have the possibility to provide the agent to a remote side:
* http-digest is generated randomly -> no possibility to login from remote
* if port is occupied, a random(?) one is selected.. I need to lookup it manually

But, if switching to sockets, it would solve these issues, because:
* user-level permissions, easy implementation in multi-user environments
* No occupied ports
* Possibility to forward the socket through nginx/apache to any static port (or using mod_rewrite) and user-defined login-auth (e.g. ldap for administrator-access)
* No password generation; Someone can login from a remote machine
* Bonus: Stale-Socket check for already running agents

What do you think?

**Comment by cdujeu** [comment]
Hum, the thing is that we are using a ready-made library for the webserver, and everything is now coded to use http, and tested successfullly for a couple of months now :-)
So it could be a future improvements/refactorisation, but I don't think it would be "as simple as that" to use a socket instead of a port.
Let's say it's ok now with this system (just implemented on both side, seems to be working right, will commit soon).
About your last concern of random access: I think we could then simply use an option for starting the program with a fixed username & password (passed as arguments), and that would make it useable.
Right?
-c

**Comment by Flauschbaellchen** [comment]
Well, I'm currently not using the remote access and I think I won't in the next few weeks, too ;)
However, I would love to see this implemented in the future, as it would simplify the auth-process and also gives more flexibility.

**Comment by cdujeu** [comment]
Ok, so you can grab the last versions (built a couple of minutes ago), the mechanism is implemented. Hopefully it won't have too many side effects, we'll see. 
It's providing an acceptable multi-user setup for Windows at least.
-c

**Comment by Flauschbaellchen** [comment]
Hi Charles,

Windows:
It works, however since I updated to the new client, it starts twice after loggin in. (Windows 7 Prof. in VirtualBox 4.3.10)
Password is correctly stored in ``C:\Users\xxxx\AppData\Roaming\Pydio\ports_config``

Linux (Ubuntu 14.04.01/KDE):
**Does not work**. No changes after installing the new package.
**No** password is stored in ``~/.pydio_data/``
MD5Sum: 566a0b0aace913e87234db5ee35e815d  agent/pydio-sync-agent-linux-latest

I downloaded the latest linux package several times to make sure I have the correct one. Can you confirm?
Any special logfiles you'd like to have?

Greetings~

**Comment by cdujeu** [comment]
Hi, 
i'm not really testing on linux currently - we may have a wrong switch somewhere. Will retest when I can.
-c

**Comment by Flauschbaellchen** [comment]
Hi charles,
any news on the linux build/dev status?
Latest build from yesterday still lacks the http-auth.

**Comment by cdujeu** [comment]
Nope, it's here. What makes you think it's not here?
But from my latest tests, the Linux agent has a lot of issues regarding encodings...

**Comment by Flauschbaellchen** [comment]
The agent within the package you provide on the download page is still the old one built on 17. Feb.
The client(UI) can connect to it but also every guest.

If downloading the 'standalone' agent from within the 'agent' directory, I get the correct one built on 24. Feb.
It provides the http-auth, however, even the client cannot connect to it:
```
QFSFileEngine::open: No file name specified
Server is "http://127.0.0.1:5556"
HTTP Poller Reply failure : "Host requires authentication"
```
I didn't found a more recent version of the client(UI).
Client: built on 17.Feb, md5sum: `323cc6609f995fdcca95690a5e0b2ec9  pydio-ui/pydio-ui
`

**Comment by cdujeu** [comment]
Hum 
There's a build issue indeed for the targz. And I think the UI and agent must be currently looking at different places to store/retrieve the password...
-c

**Comment by Flauschbaellchen** [comment]
Downloaded last package built yesterday and still the same issues...
Is this still on highest priority?

**Comment by cdujeu** [comment]
Hi
Tried to fix it but I still have an issue I don't understand. Agent and UI don't search the config file in the same location. Still investigating.
-c

**Comment by cdujeu** [comment]
@Flauschbaellchen ha ha I think the UI is not correctly rebuilt ... it's still and old binary being packed...
Stay tuned, i'll fix that

**Comment by cdujeu** [comment]
Ok the package is now updated, working for me.

**Comment by Flauschbaellchen** [comment]
Hi charles,

Sorry, but it doesn't work for me:

```
Trying to start agent
  -- HTTPMANAGER --   :     "Server set to http://127.0.0.1:5556"
  -- HTTPMANAGER --   :     "Username set to "
  -- HTTPMANAGER --   :     "HTTP Poller Reply : Host requires authentication"
  -- HTTPMANAGER --   :     "HTTP Poller Reply : Host requires authentication"
  -- HTTPMANAGER --   :     "HTTP Poller Reply : Host requires authentication"
  -- HTTPMANAGER --   :     "-----------------------MAX CONNECTION ATTEMPTS REACHED, CLEARING JOBS-----------------------"
UPDATING PORTS FROM CONFIG FILE
  -- HTTPMANAGER --   :     "Server set to http://127.0.0.1:5556"
  -- HTTPMANAGER --   :     "Username set to "
  -- HTTPMANAGER --   :     "HTTP Poller Reply : Host requires authentication"
  -- HTTPMANAGER --   :     "HTTP Poller Reply : Host requires authentication"
  -- HTTPMANAGER --   :     "HTTP Poller Reply : Host requires authentication"
[...]
```

I tried a clean install by deleting ~/.pydio and ~/.pydio_data, but after restarting agent+ui it won't recreate those folders.

**Comment by cdujeu** [comment]
is it really <username> or replaced by your username??

**Comment by Flauschbaellchen** [comment]
The ```<username>``` is replaced by my local login name. The directory doesn't exist.

**Comment by cdujeu** [comment]
mmm, indeed, I don't know why, it's storing in .config/Pydio instead of .local/share/pydio

**Comment by cdujeu** [comment]
let's open a new dedicated issue for that
