### ISSUE TITLE
ValueError: No JSON object could be decoded

### ISSUE THREAD

**Issue by hitchhiker** [pydio/pydio-sync#79]
I've been trying for 2 days to get *any* version of pydiosync(+-java) working with a big directory 100k/200gb

Currently I'm back to trying to get this pre-alpha to connect. I've never got past the connection setup screen. No matter what I try it just either a) returns to the login/pass screeen when i click connect or b) tells me my credentials are wrong.

Web interface/connectivity all fine.
I just discovered the log file, in there I'm seeing: ValueError: No JSON object could be decoded - which is obviously indicating a null instance of some sort of response from the rest?? api or whatever is being used.

Is there any guide for setting up pydio 6 on win2008 / to work with pydiosync (pre-alpha)?

**Comment by cdujeu** [comment]
Hello Hitchiker
You very probably have a server-side issue.
Can you check the web.config described in https://pyd.io/configure-applicationpool-for-pydio-in-windows2012-iis8/ ? 
Plus the forum thread https://pyd.io/f/topic/must-read-pydiosync-making-sure-server-api-is-working/ ? 

Thank you to use the forum to ask questions like that, and post here only once a real bug is detected. I close that one for the moment :-)
-c
